jQuery(document).ajaxComplete(
	function(e,x,s)
	{
		jscolor.installByClassName('jscolor');
	}
);
jQuery(document).ready(
	function(e,x,s)
	{
		jscolor.installByClassName('jscolor');
	}
);
