name: WordPress Coding Standards Checks

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: PHP 5.6 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '5.6'

        - name: PHP 7.0 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.0'

        - name: PHP 7.1 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.1'

        - name: PHP 7.2 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.2'

        - name: PHP 7.3 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.3'

        - name: PHP 7.4 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '7.4'

        - name: PHP 8.0 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.0'

        - name: PHP 8.1 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.1'

        - name: PHP 8.2 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.2'

        - name: PHP 8.3 Check
          uses: shivammathur/setup-php@v2
          with:
            php-version: '8.3'

        - name: WPCS Check
          uses: 10up/wpcs-action@stable
          with:
            excludes: 'Tests'
