name: WordPress Coding Standards Checks

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        
        - name: Install PHP 5.6
          uses: shivammathur/setup-php@v2
          with:
            php-version: '5.6'
            tools: phpcs

        - name: Run phpcs
          run: phpcs .

        - name: WPCS Check
          uses: 10up/wpcs-action@stable
          with:
            excludes: 'Tests'
