name: WordPress Coding Standards Checks

on: push

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: WPCS Check
          uses: 10up/wpcs-action@stable
          with:
            excludes: 'Tests'
            enable_warnings: true

        - name: PHP compat
          uses: pantheon-systems/phpcompatibility-action@v1
          with:
            test-versions: 5.6-
          if: always()
